---
Name: goldfinch-bugtracker
---

SilverStripe\Control\RequestHandler:
  extensions:
    - Goldfinch\BugTracker\Extensions\BugHandlerExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Goldfinch\BugTracker\Extensions\SiteConfigExtension


---
Name: goldfinch-bugtracker-icon
Only:
  moduleexists: 'goldfinch/enchantment'
---

Goldfinch\BugTracker\Admin\BugTrackerAdmin:
  icon: 'bi-bug-fill'

