---
Name: goldfinch-bugtracker
---

SilverStripe\Control\RequestHandler:
  extensions:
    - Goldfinch\BugTracker\Extensions\BugHandlerExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Goldfinch\BugTracker\Extensions\SiteConfigExtension
